### ISSUE TITLE
Request headers

### ISSUE THREAD

**Issue by raxkin** [bsnk-dev/pnwkit#8]
Return the response headers, or provide a option to see the rate limit.

Maybe store that internally and provide a value like `pnwkit.rateLimitRestAfter`  if it's possible to change de result definition of the queries.
This are the headers descriptions that were published on discord:
- X-RateLimit-Reset-After - The number of seconds until the rate limit resets.
- X-RateLimit-Limit - The maximum number of requests per rate limit period.
- X-RateLimit-Remaining - The remaining number of requests before the rate limit is reached. If this reaches zero you should wait the number of seconds in X-RateLimit-Reset-After before attempting another request.
- X-RateLimit-Reset - The unix timestamp at which point the rate limit resets.

**Comment by bsnk-dev** [comment]
Thank you for bringing this to my attention. This will be implemented soon. 🙂

**Comment by bsnk-dev** [comment]
@raxkin Do you want to look over the PR #9 to see if the implementation fits your needs?

**Comment by raxkin** [comment]
Yep, it's fine, thanks!
